# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    session: true
    
    # CRITICAL: Add this for ALL environments, not just test

    
    # ... rest of your config

when@test:
    framework:
        # This can stay, but http_method_override should be above
        session:
            storage_factory_id: session.storage.factory.mock_file