# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers:
        - x-forwarded-for
        - x-forwarded-proto
        - x-forwarded-host
        - x-forwarded-port

    session:
        enabled: true
        cookie_secure: auto
        cookie_samesite: lax
        cookie_httponly: true

when@test:
    framework:
        session:
            storage_factory_id: session.storage.factory.mock_file
